import{a as H,S as q,i as d}from"./assets/vendor-KnZd4sWe.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))i(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();const E="48897668-7102e16b6983a9d2c1f1ac079",P="https://pixabay.com/api/";async function f(e,t=1,o=40){try{const i=await H.get(P,{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:o,page:t}});return i.data.hits.length===0?{images:[],totalHits:0}:{images:i.data.hits,totalHits:i.data.totalHits}}catch(i){return console.error("❌ Error fetching images:",i),{images:[],totalHits:0}}}const h=document.querySelector(".gallery"),$=new q(".gallery a");function m(e){const t=e.map(({webformatURL:o,largeImageURL:i,tags:s,likes:r,views:c,comments:S,downloads:w})=>`
      <div class="gallery-item">
        <a href="${i}" class="gallery-link">
          <img src="${o}" alt="${s}" loading="lazy" class="gallery-image" />
        </a>
        <div class="info">
          <p class="info-item"><b>❤️ Likes:</b> ${r}</p>
          <p class="info-item"><b>👀 Views:</b> ${c}</p>
          <p class="info-item"><b>💬 Comments:</b> ${S}</p>
          <p class="info-item"><b>📥 Downloads:</b> ${w}</p>
        </div>
      </div>
    `).join("");h.insertAdjacentHTML("beforeend",t),$.refresh()}function y(){h.innerHTML=""}const p=document.querySelector("#search-form");document.querySelector(".gallery");const a=document.querySelector("#load-more"),L=document.querySelector("#loader");let l="",n=1;const u=40;a.classList.add("is-hidden");function b(){L.classList.remove("is-hidden")}function v(){L.classList.add("is-hidden")}function g(e){e<=u*n?(a.classList.add("is-hidden"),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):a.classList.remove("is-hidden")}p.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements.searchQuery.value.trim(),n=1,y(),a.classList.add("is-hidden"),l){b();const{images:t,totalHits:o}=await f(l,n,u);v(),t.length>0?(m(t),g(o)):d.error({message:"Sorry, no images found!"})}});a.addEventListener("click",async()=>{n+=1,b();const{images:e,totalHits:t}=await f(l,n,u);v(),e.length>0?(m(e),g(t)):(a.classList.add("is-hidden"),d.info({message:"We're sorry, but you've reached the end of search results."}))});function O(){const e=document.querySelectorAll(".gallery-item");if(e.length>0){const t=e[0].getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}p.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements.searchQuery.value.trim(),n=1,y(),a.classList.add("is-hidden"),l){const{images:t,totalHits:o}=await f(l,n,u);t.length>0?(m(t),g(o)):d.error({message:"Sorry, no images found!"})}});a.addEventListener("click",async()=>{n+=1;const{images:e,totalHits:t}=await f(l,n,u);e.length>0?(m(e),O(),g(t)):(a.classList.add("is-hidden"),d.info({message:"We're sorry, but you've reached the end of search results."}))});
//# sourceMappingURL=index.js.map
